config/routes.rb
ServiceHealthDashboard::Application.routes.draw do
  
  

  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  if Rails.env == 'production'
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end

  get "events/index"

  get "statuses/index"

  root :to => 'Services#index'

  get "services/index"
  
  resources :events, only: [:new, :create, :index, :show, :edit, :update]
  resources :services#, except: :show
  resources :statuses
  match '/expire', to: 'services#expire', as: 'expire'
  match '/1', to: 'services#nf1', as: 'nf1'
  match '/2', to: 'services#nf2', as: 'nf2'
  #match '/admin', to: 'services#admin', as: 'admin'
  #match '/:slug', to: 'services#show', as: 'services_slug_path'


end

app/models/service.rb
class Service < ActiveRecord::Base
	#belongs_to :dependent
  has_many :events
	attr_accessible :description, :name, :order, :slug, :version, :invisible, :service_id#, :dependent

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def self.platform_maintenance(nf_version)
    Event.includes(:service).
          where(:events=> {:invisible=>false}).
          where(start: (DateTime.now-12.hours)..DateTime.now+90.days).
          where(status_id: 2).
          where(:services => {:version=> nf_version}).
          order('start')
  end


  def self.maintenance(service)
    Event.where(:events=> {:invisible=>false}).
          where(start: (DateTime.now)..DateTime.now+90.days).
          where(status_id: 2).
          where(:service_id => service).
          order('start')
  end

	def current_status
		e = Event.where('service_id = ?', self.id.to_s).
              where('start < ? ', DateTime.now).
              where('invisible = ?', false).
              order('start').last
    if e == nil
      e = most_recent_event(DateTime.now)
    end

    e

	end

  def most_recent_event(date)
    e = Event.where('service_id = ?', self.id.to_s).
              where('invisible = ?', false).
              where('start <= ?', date).
              order('start').last
    e == nil ? nil : e
  end

	def most_severe_event_for_date(date)
    events = Event.where('service_id = ?',self.id.to_s).
                  where('invisible = ?', false). 
                  where(start: date.beginning_of_day()..date.end_of_day()).
                  order('status_id DESC').
                  first

    if events == nil
      events = self.most_recent_event(date)
    end

    events

	end

  def x_days_statuses(days_to_go_back)
    events = []
    day = DateTime.now - days_to_go_back.days
    days = (day .. day + days_to_go_back).to_a { |date|  '#{date}' }

    #adds a second 'today' for displaying the current status vs the daily severity status
    days << days.last
    days.reverse!

    for day in days
      events << most_severe_event_for_date(day)
    end
    events
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_filter :authenticate_user!, :only => [:create, :new, :update, :edit, :admin]

  caches_action :index, :show, :nf1, :nf2, :expires_in => 3.minutes



  def date_range
    days_to_go_back = 3
    @day = DateTime.now - days_to_go_back
    @days = (@day .. @day + days_to_go_back).to_a { |date| '#{date}' }
    @days.reverse!
  end

  def expire
    expire_action :action=>:index
    redirect_to '/'
  end

  def index
  	@nf1_services = Service.where('version=1 AND invisible=false').all
  	@nf2_services = Service.where('version=2 AND invisible=false').all
  	@statuses = Status.all
  	@maintenance = Event.maintenance
    days = date_range
    
  end


  def show
    @service = Service.find(params[:id])

    @events = Event.where('service_id='+@service.id.to_s).
                    where('start < ?', DateTime.now).
                    where('start >= ?', DateTime.now-4.days).
                    where('invisible = ?', false).
                    order('start DESC')

    @maintenance = Service.maintenance(@service.id).
                    order('start DESC')

    respond_to do |format|
      format.html { render :template => 'services/show' }
      format.json { render json: @service }
    end
  end

  def nf1
    @nf1_services = Service.where('version=1 AND invisible=false').all
    @statuses = Status.all
    @maintenance = Service.platform_maintenance(nf_version=1)
    days = date_range
  end

  def nf2
    @nf2_services = Service.where('version=2 AND invisible=false').all
    @statuses = Status.all
    @maintenance = Service.platform_maintenance(nf_version=2)
    days = date_range
  end

  def admin
    respond_to do |format|
      format.html 
    end
  end


  def edit
    @service = Service.find(params[:id])
  end


  def new
    @service = Service.new

    respond_to do |format|
      format.html 
      format.json { render json: @service }
    end
  end   

  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to '/', notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: 'new' }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])

        format.html { redirect_to '/', notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end


end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_eventstable.html.erb
<% for e in events %>
  <% if request.params[:status].to_i == e.id %>
    <tr class="moreinfo">
  <%else%>
    <tr>
  <%end%>
    <% if e.message %>
      <td>
        <%= e.start.strftime("%b %d, %I:%M%P")  %> <a id="<%= e.id %>"/><br />
        <td class="status">
                <%= image_tag("status/"+e.status.image+".png", alt: e.status.image)%>
        </td>
        <td><%= e.message%></td>
      </td>
    <% else %>
      <td><%= e.start.strftime("%b %d, %I:%M%P") %> <a id="<%= e.id%>"/></td>
      <td class="status highlight">
        <% if e.informational %>
          <img src="{{ STATIC_URL }}images/status/information.png" alt="Information">
        <% else %>
          <%= image_tag("status/"+e.status.image+".png", alt: e.status.image)%>
        <% end %>
      </td>
      <td><%= e.message%></td>
    <%end%>
  </tr>
<% end %>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name" %><br />
    <%= f.text_field :name%>
  </div>
  <br />

  <div class="field">
    <%= f.label :description, "Description" %><br />
    <%= f.text_field :description%>
  </div>
  <br />


  <div class="field">
    <%= f.label :slug, "Slug" %><br />
    <%= f.text_field :slug %>
  </div>
  <br />

  <div class="field">
    <%= f.label :version, "Version" %><br />
    <%= f.text_field :version %>

  </div>
  <br />

  <div class="field">
    <%= f.label :invisible, "Invisible" %><br />
    <%= f.check_box :invisible %>
  </div>
  <br />

  <div class="field">
    <%= f.label :order, "Order" %><br />
    <%= f.text_field :order, default:1 %>
  </div>
  <br />


  <div class="actions">
    <%= f.submit 'Create', class: 'btn btn-primary'%>
  </div>
  <br />

<% end %>

app/views/services/_legend.html.erb
<div id="current_time"><small><b>All time shown is Sydney, Australia time.</b><br /><i>Current time:  <%= Time.zone.now.strftime("%b %d, %I:%M%P") %> </i></small></div>
<div class="legend" id="legend">
  <h4> Legend </h4>
  <table class="legend">
    <tbody id="legend-body">
      <% for status in @statuses %>
      <tr>
        <td class="icon" align="center">
          <%= image_tag("status/"+status.image+".png", :alt => status.name) %>
        </td>
        <td><%= status.description %></td>
      </tr>
      <%end%>
      <tr>
        <td align="center" class="Hazard">
          Hazard
        </td>
        <td>This scheduled  maintenance should not impact service</td>
      </tr>
      <tr>
        <td align="center" class="Critical">
          Critical
        </td>
        <td>This scheduled maintenance will impact service</td>
      </tr>

    </tbody>
  </table>
</div>

app/views/services/_nf1.html.erb
<% if @nf1_services %>
<h2 id="heading" style="font-size: 26px;">Original Ninefold</h2>
	<table id="service-list">
            <colgroup>
            <col />
            <col style="background-color: #F3F3F3; width: 120px;" />
            <col />
            <col />
            <col />

          </colgroup>
          <thead>
            <tr>
              <th>Service</th>
              <th class="today">Current</th>
			  <% for day in @days %>
			  	<th class="date"><%= day.strftime("%d/%m") %></th>
			  <%end%>
			</tr>
	      </thead>
	      <tbody id="services-body">
			<% for service in @nf1_services %>
				<%= render partial: 'servicestable', :locals=> {service: service} %>
			<% end %>     
		</tbody>
	</table>
<%end%>		

app/views/services/_nf2.html.erb
<% if @nf2_services %>
<h2 id="heading" style="font-size: 26px;">Ninefold</h2>
<table id="service-list">
  <colgroup>
  <col />
  <col style="background-color: #F3F3F3; width: 120px;" />
  <col />
  <col />
  <col />

</colgroup>
<thead>
  <tr>
    <th>Service</th>
    <th class="today">Current</th>
    <% for day in @days %>
    <th class="date"><%= day.strftime("%d/%m") %></th>
    <%end%>
  </tr>
</thead>
<tbody id="services-body">
  <% for service in @nf2_services %>
  <%= render partial: 'servicestable', :locals=> {service: service} %>
  <% end %>     
</tbody>
</table>
<%end%>   

app/views/services/_servicestable.html.erb
  <tr>
    <td><a href="/services/<%=service.slug%>"><%= service.name %></td>
    <% service.x_days_statuses(3).each_with_index do |e,i| %>
      <% if e.nil? %>
          <td class="status" style="width: 100px;">
            <div>
              <%= image_tag("status/tick-circle.png") %>
            </div>
          </td>
      <% else %>
        <% if i == 0 %>
          <td class="status" style="width: 100px;">
            <div>
                <% if service.events.nil? %>
                  <%= image_tag("status/tick-circle.png") %>
                <% else %>
                  <% if service.current_status.nil? %>
                    <%= image_tag("status/tick-circle.png") %>
                  <% else %>
                    <%= image_tag("status/"+service.current_status.status.image+".png", alt: service.current_status.status.name)%>
                    <% if service.current_status.status.image != 'tick-circle' %>
                      <div style="font-size:9px;">
                        <% link_text = "/services/" + service.slug + "?status=" + service.current_status.id.to_s %>
                        <a href="<%= link_text %>" style="border-bottom: dotted;border-bottom-width: 1px; text-decoration: none;">(more info)</a>
                      </div>
                    <% end %>
                  <% end %>
                <% end %>
            </div>
          </td>
        <% else %>
          <td class="status" style="width: 100px;">
            <div>
              <%= image_tag("status/"+e.status.image+".png", alt: e.status.name) %>
                <% if e.status.image != 'tick-circle' %>
                  <div style="font-size:9px;">
                    <a href="/services/<%=service.slug%>?status=<%=e.id%>" style="border-bottom: dotted;border-bottom-width: 1px; text-decoration: none;">(more info)</a>
                  </div>
                <% end %>
            </div>
          </td>
        <% end %>
      <% end %>
    <% end %>
  </tr>

app/views/services/_upcoming.html.erb
<div align="left" style="margin-top: 30px;" id="heading_maintenance"><h4 style="font-size: 16px;">Scheduled Maintenance</h4></div>
 <table id="service-list2" class="event-log" style="margin-top:10px;">
        <thead>
            <tr>
                <th style="text-align: center; width: 80px;">Time</th>
                <th class="date" style="border-right: none;">Detail</th>
            </tr>
        </thead>
        <tbody id="services-body">
        	<% if !@maintenance.empty? %>
        		<% for event in @maintenance %>
                    <% if event!= nil %>
                	   <tr>
                    		<td class="status"><%= event.start.strftime("%b %d, %I:%M%p")%><br />
                    			<div style="font-size:11px;">
                                    <% link_text = "/services/" + event.service.slug + "?status=" + event.status.id.to_s %>
                    				<a href="<%= link_text %>" style="border-bottom: dotted;border-bottom-width: 1px; text-decoration: none;">(more info)</a>
                    			</div>
                    		</td>

                    		<td class="status">
                                <% if event.event_type != nil %>
                                    <% event.event_type %>
                                    <div class="upcoming <%=event.event_type.name%>"><%=event.event_type.name%></div>
                                <%end%>

                    			<div id="service" style="font-weight: bold;">
                    				<%= event.service.name %>
                                </div>
                    			<%=event.message%>
                    		</td>
                    	</tr>
                    <% end %>
                <%end%>
            <%else%>
            <tr>
        		<td colspan=3 class="status" >No Scheduled Maintenance</td>
        	</tr>
        	<%end%>
        </tbody>
  </table>

app/views/services/admin.html.erb
<div id="webservices" class="frame">
<h1>Admin</h1>
<table>
  <tr>
    <td><%= link_to "New Event", new_event_path %></td>
  </tr> 
  <tr>
    <td><%= link_to "View Events", events_path %></td>
  </tr> 
  <tr>
    <td><%= link_to "Change Password", edit_user_registration_path %></td>
  </tr> 
  <tr>
    <td><%= link_to "Logout", destroy_user_session_path %></td>
  </tr> 
</table>
</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<div id="webservices" class="frame">
<%= render 'nf2' %>
<%= render 'nf1' %>
<%= render 'upcoming' %>
<%= render 'legend' %>
</div>

app/views/services/new.html.erb
<h1>Create a Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/nf1.html.erb
<div id="webservices" class="frame">
<%= render 'nf1' %>
<%= render 'upcoming' %>
<%= render 'legend' %>
</div>

app/views/services/nf2.html.erb
<div id="webservices" class="frame">
<%= render 'nf2' %>
<%= render 'upcoming' %>
<%= render 'legend' %>
</div>

app/views/services/show.html.erb
<div id="webservices" class="frame">
  <h2><%= @service.name %></h2>
  <p id="serviceDescription"><%= @service.description %></p>        
    <table class="event-log" cellpadding="10">
      <thead>
        <tr>
          <th class="time-header">Time</th>
          <th class="status-header">Status</th>
            <th>Detail</th>
        </tr>
      </thead>
      <tbody id="events-tbody">
        <td colspan=3 style="background-color: #ddd;">Past events</td>
        <% unless @events.empty? %>
          <%= render partial: 'eventstable', :locals=> {events: @events} %>
        <% else %>
          <tr>
            <td colspan=3>No events to display</td>
          </tr>
        <% end %>
        <td colspan=3 style="background-color: #ddd;">Future events</td>
        <% unless @maintenance.empty? %>   
          <%= render partial: 'eventstable', :locals=> {events: @maintenance} %>
        <% else %>
          <tr>
            <td colspan=3>No events to display</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div id="current_time"><small><b>All time shown is Sydney, Australia time.</b><br /><i>Current time:  <%= Time.zone.now.strftime("%b %d, %I:%M%P") %> </i></small></div>
    <div id="go_back" style="margin-top: 20px;"><a href="/"><< Back to Overview </a></div>
</div>