config/routes.rb
ServiceHealthDashboard::Application.routes.draw do
  
  

  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  if Rails.env == 'production'
    devise_for :users, :controllers => { :registrations => "registrations" } 
  else
    devise_for :users
  end

  get "events/index"

  get "statuses/index"

  root :to => 'Services#index'

  get "services/index"
  
  resources :events, only: [:new, :create, :index, :show, :edit, :update]
  resources :services#, except: :show
  resources :statuses
  match '/expire', to: 'services#expire', as: 'expire'
  match '/1', to: 'services#nf1', as: 'nf1'
  match '/2', to: 'services#nf2', as: 'nf2'
  #match '/admin', to: 'services#admin', as: 'admin'
  #match '/:slug', to: 'services#show', as: 'services_slug_path'


end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :service
  belongs_to :status
  belongs_to :event_type
  #belongs_to :incident
  attr_accessible :informational, :invisible, :message, :start, :service_id, :event_type_id, :status_id
  after_create :schedule




  def self.maintenance
  	where(start: (Time.now.utc-12.hours)..90.days.from_now.end_of_day).
  		where(invisible: false).
  			where(status_id: 2)
  end
  def to_s
    message
  end

  private

  def schedule
    if self.start > DateTime.now && self.invisible = true
      es = EventScheduler
      p "Scheduling event expose in "+(self.start - DateTime.now).abs.round.to_s
      Resque.enqueue_in((self.start - DateTime.now).abs.round, es, self.id)
    end
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  attr_accessible :name, :event_type_id
end

app/controllers/events_controller.rb
require 'time'


class EventsController < ApplicationController
  before_filter :authenticate_user!, :only => [:create, :new, :index, :show, :edit, :update]


  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])

        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
  	@events = Event.order('-start')
  end


  def edit
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end  	

  def create
    @event = Event.new(params[:event])
    respond_to do |format|
      if @event.save
        format.html { redirect_to '/', notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start, "Start" %><br />
    <%= f.text_field :start%>
  </div>
  <br />
  <div class="field">
    <%= f.label :service, "Service" %><br />
    <%= f.collection_select :service_id, Service.all, :id, :name %>

  </div>
  <br />
  <div class="field">
    <%= f.label :status, "Status" %><br />
    <%= f.collection_select :status_id, Status.all, :id, :name %>

  </div>
  <br />

  <div class="field">
    <%= f.label :message, "Message" %><br />
    <%= f.text_area :message, :rows=>10, :cols=>40 %>

  </div>
  <br />
  <div class="field">
    <%= f.label :event, "Event Type" %><br />
    <%= f.collection_select :event_type_id, EventType.all, :id, :name, :include_blank => true %>

  </div>
  <br />

  <div class="field">
    <%= f.label :invisible, "Invisible" %><br />
    <%= f.check_box :invisible %>
  </div>
  <br />
  
  <div class="actions">
    <%= f.submit :class=>"btn btn-primary" %>
  </div>
  <br />

<% end %>

<script type="text/javascript">
  $(function() {
    $('#event_start').datetimepicker({
      showOn: "button",
      buttonImage: "/assets/calendar.png",
      buttonImageOnly: true,
      dateFormat: "yy MM d",
      timeFormat: "h:mmtt" 
    })
  });
</script>

app/views/events/edit.html.erb
<div id="webservices" class="frame">
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<div id="webservices" class="frame">
<h1>Listing events</h1>
<div id="webservices">
<table id="service-list">
  <tr>
    <th>Service</th>
    <th>Description</th>
    <th>Date</th>
    <th>Status</th>
    <th>Edit</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.service.name %></td>
    <td><%= event.message %></td>
    <td><%= event.start %></td>
    <td><%= event.status.name %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
  </tr>
<% end %>
</table>

<br />
</div>
<%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<div id="webservices" class="frame">
<h1>Create an Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event.message %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>